id: test
version: -1
name: test
starttaskid: "0"
description: ""
tasks:
  "0":
    id: "0"
    taskid: f4b3ff67-4f3a-4f09-8840-bece75071ec2
    type: start
    task:
      id: f4b3ff67-4f3a-4f09-8840-bece75071ec2
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 22df2427-c7d9-43ba-8853-d5a0ea760741
    type: regular
    task:
      id: 22df2427-c7d9-43ba-8853-d5a0ea760741
      version: -1
      name: Untitled Task
      description: Ask a user a question via email and process the reply directly
        into the investigation.
      scriptName: EmailAskUser
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      additionalOptions: {}
      attachIds: {}
      bcc: {}
      bodyType: {}
      cc: {}
      email: {}
      message: {}
      option1: {}
      option2: {}
      persistent: {}
      playbookTaskID: {}
      replyAddress: {}
      replyEntriesTag: {}
      retries: {}
      roles: {}
      subject: {}
      task: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 470,
          "y": 240
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 285,
        "width": 400,
        "x": 450,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
fromversion: 5.0.0
tests:
- No tests (auto formatted)
